Update OpenTOPAS_quickStart_MacOS.md
OpenTOPAS/OpenTOPAS pull request #46
Opened 2024-07-08 18:35 UTC by JoseRamosMendez

Fixes broken links #issue https://github.com/OpenTOPAS/OpenTOPAS/issues/41#issuecomment-2214091690

2024-07-08 18:37 UTC, tmasilela approved these changes

2024-07-08 18:47 UTC, tmasilela requested changes
Directory benchmark should be 'benchmarks'

2024-07-09 17:43 UTC, JoseRamosMendez commented
Fixed typo "benchmark"

2024-07-09 17:51 UTC, tmasilela approved these changes

2024-07-09 18:02 UTC, merged